# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.6

    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbairplane